baseURL: http://ahmeedben.github.io/llmfacile
languageCode: en-us
title: LLM Facile
theme: PaperMod

params:
    homeInfoParams:
        Title: Hi there wave
        Content: Can be Info, links, about...

    socialIcons: # optional
        - name: twitter
          url: https://twitter.com
        - name: github
          url: https://github.com/ahmeedben
